import Nav from './Nav.jsx';
import Watermark from './Watermark.jsx';
import { AmbientCA1D } from './AmbientCA.jsx';

export default function Home() {
  return (
    <>
      <Nav active="home" />
      <Watermark>
        {' '}Heads up — the writing on this page was generated by an LLM. It's describing real, runnable
        code and data, not asserting anything on its own authority. Check the{' '}
        <a href="https://github.com/mbilokonsky/groovy-commutator">source</a> if it matters to you.
      </Watermark>

      <main style={{ maxWidth: 880, margin: '0 auto', padding: '2rem 1.25rem 4rem' }}>
        <section style={{ padding: '1.6rem 0 0.5rem' }}>
          <div className="gc-mono" style={{ textTransform: 'uppercase', letterSpacing: '.09em', fontSize: '0.78rem', fontWeight: 700, color: 'var(--accent)', marginBottom: '0.7em' }}>
            boolean calculus &middot; instruments &middot; open questions
          </div>
          <h1 style={{ fontFamily: "'Lora',serif", fontSize: 'clamp(1.9rem,5vw,2.6rem)', lineHeight: 1.25, margin: '0 0 0.5em', fontWeight: 600, letterSpacing: '-0.01em' }}>
            One operation on bits. A surprising number of things fall out of it.
          </h1>
          <p style={{ fontSize: '1.12rem', color: 'var(--ink-soft)', margin: '0 0 1.8em', maxWidth: '62ch' }}>
            Every state here is a row of bits, and almost everything is built from a single operation &mdash; XOR.
            From that alone: a derivative, an integral, a commutator that turns out to behave like the one in quantum
            mechanics, rules that mutate their own rulebook, and a handful of genuinely open questions about what
            happens when two of these systems are made to interact.
          </p>

          <AmbientCA1D />

          <div className="gc-cta" style={{ display: 'flex', gap: '0.8rem', flexWrap: 'wrap', margin: '1.8em 0 0' }}>
            <a href="concepts.html" className="gc-mono" style={{ display: 'inline-block', fontWeight: 700, fontSize: '0.92rem', textDecoration: 'none', padding: '0.7rem 1.3rem', borderRadius: 7, border: '1px solid var(--accent)', background: 'var(--accent)', color: '#fff' }}>
              Learn the calculus &rarr;
            </a>
            <a href="questions.html" className="gc-mono" style={{ display: 'inline-block', fontWeight: 700, fontSize: '0.92rem', textDecoration: 'none', padding: '0.7rem 1.3rem', borderRadius: 7, border: '1px solid var(--accent)', background: 'transparent', color: 'var(--accent)' }}>
              See what we've asked
            </a>
          </div>
        </section>

        <section style={{ padding: '2rem 0 0.5rem', borderTop: '1px solid var(--rule)', marginTop: '2rem' }}>
          <p style={{ fontSize: '1rem', color: 'var(--ink-soft)', margin: 0 }}>
            Prefer to build something instead of reading about it? The{' '}
            <a href="explorer.html" style={{ color: 'var(--accent)' }}>explorer</a> runs every instrument on this
            site live in your browser, in 1D or 2D, and lets you wire their outputs into each other.
          </p>
        </section>
      </main>

      <footer className="gc-footer">
        <div className="gc-footer-inner">
          Source, library code, and full research notes live in the{' '}
          <a href="https://github.com/mbilokonsky/groovy-commutator">GitHub repository</a>.
        </div>
      </footer>
    </>
  );
}
